// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgiTUAHBsWx1gMVtH_M_Hm4k0nByBOxzE',
    appId: '1:55150659522:web:4f7f4e28d92afba786785b',
    messagingSenderId: '55150659522',
    projectId: 'lueesa-app',
    authDomain: 'lueesa-app.firebaseapp.com',
    storageBucket: 'lueesa-app.appspot.com',
    measurementId: 'G-G1JVY2KQVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBab-wgyXx1fEA0RzuwN_HP6WK1M92870s',
    appId: '1:55150659522:android:7fd3e697ab6e207486785b',
    messagingSenderId: '55150659522',
    projectId: 'lueesa-app',
    storageBucket: 'lueesa-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_yodwBrXpVmV8eodW-Wlbm_7A37_eYs',
    appId: '1:55150659522:ios:653a59f7e54ebe1b86785b',
    messagingSenderId: '55150659522',
    projectId: 'lueesa-app',
    storageBucket: 'lueesa-app.appspot.com',
    iosBundleId: 'com.example.lueesaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_yodwBrXpVmV8eodW-Wlbm_7A37_eYs',
    appId: '1:55150659522:ios:8d027fa1e8f5feb686785b',
    messagingSenderId: '55150659522',
    projectId: 'lueesa-app',
    storageBucket: 'lueesa-app.appspot.com',
    iosBundleId: 'com.example.lueesaApp.RunnerTests',
  );
}
